#!/usr/bin/python

# See TestFrameUtils.py for get_args_as_string(frame0) and lldbutil.print_stacktrace(thread)
# See lldb-vscode/lldb-vscode.cpp


import lldb
import shlex
import optparse
from sys import __stdout__

from re import compile, VERBOSE, search, sub


# 7/8-bit C1 ANSI sequences
ansi_escape = compile(
    br'(?:\x1B[@-Z\\-_]|[\x80-\x9A\x9C-\x9F]|(?:\x1B\[|\x9B)[0-?]*[ -/]*[@-~])'
)

def escape_ansi(line):
    return ansi_escape.sub(b'', bytes(line))

def escapeQuotes(res):
    res = escape_ansi(res.encode("utf-8", "replace"))
    res = str(res.decode("utf-8"))
    res = res.replace('"', '\\\"')
    res = res.replace("'", '\\\"')
    return res

def vimOutCb(res, data = ''):
    """ Escape sequence to trap into Vim's cb channel.
        See :help term_sendkeys for job -> vim communication """
    print('\033]51;["call","Lldbapi_LldbOutCb", ["{}", "{}"]]\007'.format(escapeQuotes(res), data))

def vimErrCb(err):
    print('\033]51;["call","Lldbapi_LldbErrCb",["{}"]]\007'.format(escapeQuotes(err)))

def get_tty(debugger, command, result, internal_dict):
    print(debugger.GetOutputFileHandle())

def set_tty(debugger, command, result, internal_dict):
    args = shlex.split(command)
    if len(args) > 0:
        path = args[0].strip()
        print('path:%s'% path)
        f = open(path, "w")
    else:
        f = __stdout__


    debugger.SetOutputFileHandle(f, True)
    debugger.HandleCommand('get_tty', result)
    print>>result, 'get_tty'
    print('new path: set')


def bp_dict(debugger, command, result, internal_dict):
    """ return a breakpoint dict of form = {'filename:line_nr': [id, id, ...]} """
    target = lldb.debugger.GetSelectedTarget()
    id_dict = {}

    for bp in target.breakpoint_iter():
        for bl in bp:
            loc = bl.GetAddress().GetLineEntry()
            key = str(loc.GetFileSpec()) + ':' + str(loc.GetLine())
            if key in id_dict:
                id_dict[key].append(bp.GetID())
            else:
                id_dict[key] = [bp.GetID()]

    vimOutCb('breakpoint updated', id_dict)
    print(id_dict)

def line_at_frame(debugger, command, result, internal_dict):
    """ return the source file's line # based on a the selected frame """
    target = lldb.debugger.GetSelectedTarget()
    if target is not None:
        process = target.GetProcess()
        for thread in process:
            frame = thread.GetSelectedFrame()
            if frame is not None:
                path = frame.GetPCAddress().GetLineEntry()
                vimOutCb('current file', path)
                print(path)
    else:
        print("Unable to get a line entry for frame")


def log_cb(msg):
    print('logging')
    vimOutCb('logging', msg)




if __name__ == '__main__':
    # create a new debugger instance if running from CLI
    lldb.debugger = lldb.SBDebugger.Create()
elif lldb.debugger:
    # initialize global setup here
    # for lldb->vim comms use vimOutCb or logging or override HandleCommand globally?
    # apropros log
    lldb.debugger.SetPrompt('(vim-lldb)')
    lldb.debugger.EnableLog('lldb', ['break'])
    #lldb.debugger.SetLoggingCallback(log_cb)

    #lldb.debugger.SetLoggingCallback(vimOutCb)

    lldb.debugger.HandleCommand('command script add -f lldb_commands.bp_dict bp_dict')
    print('The "bpdict" command has been installed')
    lldb.debugger.HandleCommand('command script add -f lldb_commands.line_at_frame line_at_frame')
    print('The "line_at_frame" command has been installed')
    lldb.debugger.HandleCommand('command script add -f lldb_commands.set_tty set_tty')
    print('The "set_tty" command has been installed')
    lldb.debugger.HandleCommand('command script add -f lldb_commands.get_tty get_tty')
    print('The "get_tty" command has been installed')


